apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sn121vhkj-go
  janus-idp.io/tekton: sn121vhkj-go
  backstage.io/kubernetes-id: sn121vhkj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sn121vhkj-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
