apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sn121vhkj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sn121vhkj-go 
  name: sn121vhkj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sn121vhkj-go 
